### ISSUE TITLE
Contract Internal Transactions

### ISSUE THREAD

**Issue by elaineo** [ethereumproject/explorer#11]
I'd like to have the Contracts page display internal transactions, but this requires modifying a node  so that the EVM processes transaction data to record resulting value transfers. 

I'm fine with modifying an EVM for use with the explorer, and having it be open source. I just wonder if a custom EVM defeats the purpose of an open-source explorer.

Pinging @whatisgravity, who is overseeing client developments.

**Comment by matthewjamesr** [comment]
@elaineo I do not think it defeats the purpose of an opensource explorer. One simple way to get around this is put a flag in both front/backends. We would need to make the modified node opensource as well. Lets assume we call the node **etcCore**. Something like `etcCore = true/false;` in params, etc. could suffice.

**Comment by elaineo** [comment]
Completed with PR #49
