### ISSUE TITLE
address page speed boost using compound index

### ISSUE THREAD

**Issue by hackmod** [ethereumproject/explorer#125]
after create `Compound Index`, the addr page get huge speed boost.

~~~.sh
$ mongo
> use blockDB
> db.Transaction.createIndex({ from: 1, blockNumber: -1});
> db.Transaction.createIndex({ to: 1, blockNumber: -1});
~~~

for example, an addr page with ~250,000 txns
- before : 300~600ms delay
- after: less than 50~100ms delay

*Credit:* this method was introduced and confirmed by @turbobit (http://explorer.gonsmine.com)
https://www.ddengle.com/esn/7443710 (written in Korean)

**Comment by shanejonas** [comment]
just want to note here that `geth` itself now keeps an index of `address -> txes` via the RPC method `geth_getAddressTransactions`: https://github.com/ethereumproject/go-ethereum/pull/475
