### ISSUE TITLE
Replace License

### ISSUE THREAD

**Issue by elaineo** [ethereumproject/explorer#13]
I've heard some criticisms re: the existing license. I don't know much about licensing agreements, but if someone has a better one to drop in, please do.

**Comment by yolandaruiz** [comment]
The licensing terms are unclear currently, they reference commit hashes that are not in the repo history and mention an MIT "branch" which is not part of the repo either.

Are there remaining parts of the code coming from upstream that were under GPLv3? If not then the license could be reset to MIT.

**Comment by elaineo** [comment]
We do not use any upstream code. I'll reset to MIT.
