### ISSUE TITLE
Web wallet user interface

### ISSUE THREAD

**Issue by realcodywburns** [ethereumproject/explorer#15]
How labor intensive would it be to make a backend user tablespace that could store private keys and a list of public addresses they watch? We can bring over most of the front end from the classic wallet as far as visuals go. I keep hearing the "Oh the is no web wallet" argument a ton lately. Lack of security on it is a little spooky though.

**Comment by elaineo** [comment]
Pretty trivial. Hold on, taking this to slack.

**Comment by matthewjamesr** [comment]
Like this idea, great feature idea @realcodywburns.

**Comment by elaineo** [comment]
Might as well add classicetherewallet's client-side wallet while we're at it. That's also nodejs/angular.

**Comment by realcodywburns** [comment]
That's the sprit! Ha ha. I'm internet less today but tomorrow I will start reskinning every thing

**Comment by elaineo** [comment]
ooh, if we're gonna have accounts and logins, that means that there should be some reliable server to host the database, because logins will only work on one server. 

Right now, @coryvmcs1 is hosting a copy of the explorer on etherhub.io. If @coryvmcs1 is okay with it, maybe etherhub.io can be the production version of the explorer?

**Comment by realcodywburns** [comment]
For the test server: When a user is signing up, couldn't we just generate a wallet private key that is based off of the same password, like in the classic wallet?

**Comment by elaineo** [comment]
Newly generated wallets are created from a random seed, so a user should not be able to generate the same wallet twice.

**Comment by realcodywburns** [comment]
Yeah, not regeneration, generate when the account is created then store the the priv key and public key in the db. Instead of the user keeping their private key it is hashed and stored on the db for them

**Comment by elaineo** [comment]
2 questions:
 - are we going to have a sufficiently reliable server that can host the DB?
 - Not totally sure about this one. I'm okay with having user accounts associated with watch lists and API keys, but I am against storing private keys on the DB, even if hashed, given that the software is open source.

**Comment by realcodywburns** [comment]
First question: no, not at this point. We would need redundant systems and raid storage.

Question 2: yes I agree, super high risk with open source . if there is a hole it will be found.

**Comment by realcodywburns** [comment]
I have got the chrome extension working from the old wallet project. It stores keys on a users computer and keeps everything client side. watch only or stored keys. Need to migrate the rpc api at some point https://github.com/realcodywburns/ETC-CX-Wallet

**Comment by elaineo** [comment]
awesome @realcodywburns . this should be merged with the classicetherwallet though, not explorer, right?

**Comment by realcodywburns** [comment]
Right, if we are continuing them as separate projects

**Comment by elaineo** [comment]
Wallet could be a submodule of explorer, that would be easiest. Are you
working on the webwallet, or is that just Julian? Do you know if there are
plans to change the design? I think it would be nice if all the ETC web
interfaces had a similar design.
