### ISSUE TITLE
this transaction has been lost 

### ISSUE THREAD

**Issue by airboat** [ethereumproject/explorer#182]
it never showed in my account all was lost please help

**Comment by airboat** [comment]
Address
0x82fBCCA801c2fd52624420a71d32CC31c938EA9f
Type
STANDARD ADDRESS
Balance
45.8189 Ether
 
45818917970000000000 Wei
 
$414.66

**Comment by mikeyb** [comment]
If you have the private key to that account you can access the funds.  Explorer is not a wallet
