### ISSUE TITLE
Visualizing Stats & Data

### ISSUE THREAD

**Issue by elaineo** [ethereumproject/explorer#2]
Feel free to add requests, etc
- Miner hash rate distribution

**Comment by elaineo** [comment]
Thread on API endpoints for mining pool data (this is more a note to myself, the server should probably fetch and store these).

https://www.reddit.com/r/EthereumClassic/comments/4w0flf/request_for_api_endpoint_info_for_etc_mining_pools/

**Comment by kimisan** [comment]
ok , http://www.epool.io/api/stats 
this api is good, I will keep push it data to my mondodb server , hour to hour.
I start to design hash rate chart.

**Comment by kimisan** [comment]
Hi @elaineo , sorry for that, for the http://www.epool.io/api/stats , this is not a standard api, it wrapped with HTML...
Can you give me a api about ETC hashrate ?

**Comment by matthewjamesr** [comment]
@kimisan @elaineo I found that Minergate (I use their pools for mining for ease of use) has a API that will provide a lot good information.

You will use the **get blockchain info** method by calling `https://api.minergate.com/1.0/etc/status`.

**Comment by kimisan** [comment]
@matthewjamesr Wow! it worked ! Thanks!

**Comment by kimisan** [comment]
The ETC hashrate chart is finished.
Please see the index.html inside the D3 folder.

**Comment by elaineo** [comment]
Also I can provide this data for you, but maybe we can make it look like a graph?
https://etherchain.org/statistics/miners

**Comment by kimisan** [comment]
no problem , ^^

**Comment by elaineo** [comment]
I added a link to your chart! it's under stats/hashrate.

Couple of questions -- the chart doesn't load unless I hit "reload". What function are you calling to initialize the chart? I'll move it to the controller.

Also -- can the Hashrate be displayed in GH/s? so there are not so many 000,000's ;)

**Comment by kimisan** [comment]
Wow, I understand why. At the first time, the chart is showed, because the bundle_hashrate.js is called, it will append D3.js chart into svg (#hashrate). 

When you move/click to other pages, the D3.js chart content is cleaned. You need to recall bundle_hashrate.js again, to append D3.js chart into svg (#hashrate). 

However, for future developing,  now I am working on wrapped function, you can move it to the controller easily. 

displayed in GH/s?  -->  No problem

**Comment by elaineo** [comment]
Sounds good!

On Sun, Aug 7, 2016 at 12:53 AM, Kimi Sian-yu Chen <notifications@github.com

**Comment by kimisan** [comment]
1. add a new function, call_hashrate_chart() to append D3.js chart into #hashrate svg
2. modify the 780G --> 780GH/s

**Comment by kimisan** [comment]
@elaineo 
By the way, I start a discussion at https://redd.it/4xu1ql
I think the http://fork.ethstats.net/ treemap, i can make a better version for ETC , but need your api support.
Another way, for World map is also a very good idea.

**Comment by elaineo** [comment]
@kimisan Awesome! Let me know what data you need!

**Comment by matthewjamesr** [comment]
@elaineo @kimisan Not sure who worked on the hashrate/difficulty component, but it's functionality is intermittent. Is this an issue for anyone else?

**Comment by elaineo** [comment]
@matthewjamesr thanks, i restarted the block-grabber on unforked.info. Looks like it's ok on etherhub.io -- have you seen it down on that server?

**Comment by matthewjamesr** [comment]
@elaineo Yes, I have and still currently see it down on both hosts.

**Comment by kimisan** [comment]
Production: etherhub.io 
> OK

Staging server: unforked.info

> Failed

**Comment by matthewjamesr** [comment]
I confirm the same.

**Comment by kimisan** [comment]
For Miner hash rate distribution, now is finished.
Please check #42 
I will keep maintain and update new function in the future.

**Comment by kimisan** [comment]
@elaineo  @matthewjamesr  @whatisgravity 
Since the hash rate distribution is finished, I am considering to make a new chart.
Could you please give me some advice?

**Comment by elaineo** [comment]
@kimisan - we could ask reddit again :)
One thing people have asked for is a hashrate chart for the open-mining-pool (https://github.com/elaineo/open-ethereum-pool). It's not totally related, but we could show hashrate-per-miner

**Comment by kimisan** [comment]
@elaineo haha,ok!
For the open-mining-pool , i am not very familiar with ember.
But I can help with the d3.js charts portion like explorer,  What do you think ?

**Comment by elaineo** [comment]
sounds good!

On Wed, Aug 31, 2016 at 8:56 AM, Kimi Sian-yu Chen <notifications@github.com

**Comment by kimisan** [comment]
Good! Let's get started! :smile:

**Comment by elaineo** [comment]
Okay, I'll ask reddit too :)
