### ISSUE TITLE
Convert unix timestamp to human readable

### ISSUE THREAD

**Issue by suselname** [ethereumproject/explorer#22]
On the Contract Address view time must be displayed in human readable format: 22 Aug 2016, 12:30. For now it is displayed in seconds since the Unix epoch. Optionally, todays transactions can be displayed like "44 minutes ago".

**Comment by elaineo** [comment]
https://github.com/ethereumproject/explorer/commit/2dad2f1e6177c366685fa207de6ad056937812fe

done
