### ISSUE TITLE
Fix Hashrate Graph Width

### ISSUE THREAD

**Issue by matthewjamesr** [ethereumproject/explorer#24]
Constrain graph to 100% of the available width with appropriate padding/margin.

http://blocks.elaineou.com/stats/hashrate

**Comment by kimisan** [comment]
Ok, I will add Responsive Design on it.

**Comment by matthewjamesr** [comment]
@kimisan am I able to close this?

**Comment by kimisan** [comment]
Can't. I am still working on it.

**Comment by elaineo** [comment]
looks good :)
