### ISSUE TITLE
Create API for miner stats

### ISSUE THREAD

**Issue by elaineo** [ethereumproject/explorer#27]
something like this:  http://etherscan.io/stats/miner?range=7

**Comment by kimisan** [comment]
Look good, but may I start it from 2D donut chart first?
By the way, may you provide me the API for ETC miner's share percentage ?

**Comment by elaineo** [comment]
Go ahead and make the chart first. If you define the API you want, I will format the output to look like what you need. I'll work on this later today.

**Comment by elaineo** [comment]
Actually, if you define all the stats you need re: miners charts, that will help me build the DB

**Comment by kimisan** [comment]
Ok, understand.
And I start to define all the stats I need.

**Comment by elaineo** [comment]
I'm now working on the server-side processing of blocks to stat recording mining stats history. (just an update)

**Comment by elaineo** [comment]
@kimisan what source are you using to record the hashrate stats? Do you prefer hosting that on your own DB, or should I build the API on the server?

**Comment by kimisan** [comment]
API on the server is bettter, I am planing changing the hashrate chart  source to API on the server

**Comment by kimisan** [comment]
Now, the chart source source is come from @matthewjamesr 's API

**Comment by elaineo** [comment]
okay, thanks. i'll create a separate db on the server for this.

On Mon, Aug 8, 2016 at 11:04 PM, Kimi Sian-yu Chen <notifications@github.com

**Comment by kimisan** [comment]
@elaineo 
Please refer to the url.
http://drawpie.com/etc_data_vis_json_format

**Comment by elaineo** [comment]
@kimisan 
Does this work for the top miners?
curl -H "Content-Type: application/json" -X POST -d '{"action":"miners"}' http://blocks.elaineou.com/stats

**Comment by kimisan** [comment]
@elaineo  @@, can you provide more information?
this commend  of "curl -H "Content-Type: application/json" -X POST -d '{"action":"miners"}'"
I am not sure how to use it @@

**Comment by elaineo** [comment]
it's an ajax post with those options. 
```
request({
    method: 'POST',
    uri: '/stats',
    multipart: [
      {
        'content-type': 'application/json',
        body: JSON.stringify({"action":"miners"})
      },
```

**Comment by kimisan** [comment]
Look like i got the empty...
Does it need run the node ./tools/grabber.js  for listen mode?
Now I just run node app.js

**Comment by elaineo** [comment]
use tools/stats.js to populate the db

**Comment by kimisan** [comment]
Ok, got it .
But I have meet two issues,
1 . { Error: Trying to open unclosed connection.
2.  Error: Aborted due to error on block number 2079026: WriteError({"code":11000,"index":0,"errmsg":"E11000 duplicate key error collection: blockDB.blockstats index: number_1 dup key

**Comment by kimisan** [comment]
For  ajax post , it can work now, can get the miner information.
success
bundle_hashrate.js:214 "[{\"_id\":\"0x9eab4b0fc468a7f5d46228bf5a76cb52370d068d\",\"count\":1},{\"_id\":\"0xa8d0e61c254efc29e9fccca3a0c28b50b556b34d\",\"count\":1},{\"_id\":\"0x929835a1a7721d4cd8be6535700e2761d898b39d\",\"count\":1},{\"_id\":\"0x0e9b9bb146e0af0174121b966a53e8f1cd20f48a\",\"count\":1},{\"_id\":\"0x8c5535afdbdeea80adedc955420f684931bf91e0\",\"count\":1}]"

**Comment by elaineo** [comment]
@kimisan : oh shoot, I forgot -- for the setInterval part at the bottom of tools/stats.js, I have it set to `0 minutes` for testing. You can change it to 10 minutes, or whatever interval you want to use for updating your data.

Also, the Error: Aborted is fine, it ends when it comes to a block it has already seen. I should have given it a friendlier message, but yeah :)

**Comment by kimisan** [comment]
@elaineo, For miner Hashrate distribution chart is under design 

By the way, can you provide Geographic coordinate api  for getting data from db, which i can make a world heatmap map of ETC activity. 

> –]finish-the-thought 3
watching http://fork.ethstats.net/ is fun; blockheights (cant wait for the epic day ETC overtakes ETH) , block intervals and hashrates and the weird shapes created in the disagram (or visualization?) below. A more elaborate version would be awesome. also anything on a world map/globe ;)

**Comment by elaineo** [comment]
I don't know how to get the geographic coordinates. Is someone out their
keeping track of all the nodes and IP addresses?

**Comment by kimisan** [comment]
Ok, i see.  track all of the nodes is not easy.

**Comment by elaineo** [comment]
I just merged this one
