### ISSUE TITLE
Response Times & Load Issues

### ISSUE THREAD

**Issue by matthewjamesr** [ethereumproject/explorer#3]
@elaineo I am starting to notice some performance issues with the explorer. Once in a while I am getting connection refused, slow load times, etc. Not sure if it the network I am using, you updating the codebase at the time I access, etc.

What infrastructure are we using? Is our Mongo instance on the same host or different?

Edit 1: I have also noticed that block/tx data is seemingly not loading.

**Comment by elaineo** [comment]
Couple of problems:
- right now database queries are slower than snail crap
- I was lazy and didn't do much in the way of error handling so it crashes

I'll work on performance issues later today, just wanted to get a basic framework out there as a springboard

**Comment by elaineo** [comment]
is it better now? I rebuilt the indexes.

**Comment by matthewjamesr** [comment]
Holy heck, great job! It screams now :). Closing this issue.
