### ISSUE TITLE
Get a domain name

### ISSUE THREAD

**Issue by elaineo** [ethereumproject/explorer#4]
It's only at blocks.elaineou.com right now because it's fast for me to create a subdomain. This is obviously not a permanent home ;)

So, I'm happy to have some other domain name point to the server if anyone wants to pick a name.

**Comment by matthewjamesr** [comment]
What about something to the tune of:

* etccrawler.io
* etcscanner.io
* etc....

**Comment by Empty2k12** [comment]
- etcexplorer.io
- etcchain.io

**Comment by realcodywburns** [comment]
4ETC.io

**Comment by elaineo** [comment]
@coryvmcs1 has offered to host a separate copy of the block explorer at http://etherhub.io/
So I propose that the current blocks.elaineou.com be relegated to Staging server, and etherhub.io can be the production one.
