### ISSUE TITLE
incorrect balance

### ISSUE THREAD

**Issue by slacknation** [ethereumproject/explorer#40]
http://etherhub.io/addr/0xb794f5ea0ba39494ce839613fffba74279579268

http://etherscan.io/address/0xb794f5ea0ba39494ce839613fffba74279579268
https://etcchain.com/addr/0xb794f5ea0ba39494ce839613fffba74279579268

**Comment by elaineo** [comment]
@slacknation balance looks the same to me.

**Comment by slacknation** [comment]
the domain http://etherhub.io/ doesn't seem to be working right. it shows all the balance as 0.0000753800 etc. the http://blocks.elaineou.com/ domain is working fine though

**Comment by slacknation** [comment]
a screenshot of what i see http://i.imgur.com/kumQAUq.jpg

**Comment by realcodywburns** [comment]
Im having the same error, with the same incorrect balance with addr 0xCe5ED529977b08f87CBc207ebC216859820461eE

**Comment by elaineo** [comment]
Whoops, the server it was running on had the env set to "development".

Thanks for letting me know!
