### ISSUE TITLE
'The bomb' chart

### ISSUE THREAD

**Issue by realcodywburns** [ethereumproject/explorer#46]
I think we should make a 'minutes till midnight ' chart that shows the estimated difficulty based off the simple moving average of network hashrate. The difficulty algo is a constant, the hashrate is the biggest x factor.

**Comment by kimisan** [comment]
Wow, good idea !

**Comment by kimisan** [comment]
The preview of 'The bomb' chart v0.1
http://imgur.com/a/UVDaP

**Comment by arvicco** [comment]
Nice one! It would be even better if in future this chart reflects the effects of bomb defusal proposals such as ECIP-1010: https://github.com/ethereumproject/ECIPs/issues/4

**Comment by kimisan** [comment]
@arvicco 
Ok, I will add the ECIP-1010 effects.
No problem.

**Comment by realcodywburns** [comment]
Super cool!

**Comment by kimisan** [comment]
The preview of 'The bomb' chart with  ECIP-1010 effects.
1. Red : 'The bomb'
2. Green :  with  ECIP-1010 effects.
http://imgur.com/H985rW4

**Comment by arvicco** [comment]
Looks great, @kimisan!

**Comment by kimisan** [comment]
The chart is finished, please check it
https://github.com/ethereumproject/explorer/pull/48
screen shot
http://imgur.com/ABjtJgg
