### ISSUE TITLE
launching web interface?

### ISSUE THREAD

**Issue by iquidus** [ethereumproject/explorer#47]
Hi everyone,

Trying to get an instance of this up and running but having some issues.

grabber is working fine, but I dont seem to be able to start the web interface?

Web3 connection established
Killed

What am I doing wrong? How should this be launched properly?

Been looking at the code, nice work, expect a deluge of pull requests from me.

**Comment by elaineo** [comment]
can you run the server? 
`node app.js`

**Comment by iquidus** [comment]
yeah but i get 

Web3 connection established
Killed

and nothing listening on port 3000 at all during the process.

I should mention I'm trying with neither etc or eth. Just wanted to check I was launching correctly, must be more params i need to change.

**Comment by elaineo** [comment]
Oh, geth needs to be running.
