### ISSUE TITLE
Hard-coded Address Data

### ISSUE THREAD

**Issue by matthewjamesr** [ethereumproject/explorer#5]
https://github.com/ethereumproject/explorer/blame/master/public/js/controllers/AddressController.js

Instead of setting the data in the view from `$scope.addrHash` values are hard-coded.

If you show me what the inside of a hash looks like I can fix this for us.

**Comment by elaineo** [comment]
not sure i understand the question.. what line numbers are you referring to?

**Comment by ealmansi** [comment]
@matthewjamesr In views/address.html, data is read from $scope.addr (not hard-coded).
This object is populated here (AddressController.js):
```
    $scope.addr = {"balance": 0, "count": 0};
    //fetch web3 stuff
    $http({
      method: 'POST',
      url: '/web3relay',
      data: {"addr": $scope.addrHash}
    }).success(function(data) {
      $scope.addr = data;
    });
```

**Comment by matthewjamesr** [comment]
@ealmansi great thanks I am new to angular haha. We need to get # transactions working and I am thinking about removing # mined unless we are planning to add a semi-official pool?

**Comment by elaineo** [comment]
@matthewjamesr re: number mined, people have requested tracking miner output so it will get populated from a separate DB
