### ISSUE TITLE
DataTables warning: table id={id} - Ajax error

### ISSUE THREAD

**Issue by realcodywburns** [ethereumproject/explorer#51]
http://etherhub.io/addr/0xCe5ED529977b08f87CBc207ebC216859820461eE

I receive a data table error when trying to view addresses.

**Comment by elaineo** [comment]
thanks, sorry just saw this. working on it.

**Comment by realcodywburns** [comment]
The issue seems to be resolved now, any other pressing issues that you need help with?

**Comment by elaineo** [comment]
nothing super urgent that i can think of...
