### ISSUE TITLE
Explorer keeps displaying "old" blocks/transactions

### ISSUE THREAD

**Issue by anhdung-le** [ethereumproject/explorer#56]
Hi, I have the issue in which the explorer keeps pointing to old blocks.
What I've done:
- Pointing tools/grabber.js and routes/web3relay.js to private chain
- Run node/grabber.js then node app.js

The app can start, but after I reset the private chain, it keeps listing the old blocks, when selected the block -> 404 error.

I tried to removed mongo db folder but the issue remained.
Where can I completely erase the blockchain database of the explorer ?

Thank you & cheers,
Anh-Dung

**Comment by elaineo** [comment]
What settings are you using for `grabber.js`? Make sure you have `latest` set to `true`.

**Comment by anhdung-le** [comment]
You mean the settings in the **config.json if** I'm correct ?
Here are they

`{
    "gethPort": 8545, 
    "blocks": [ {"start": 0, "end": "latest"}],
    "quiet": false,
    "terminateAtExistingDB": true,
    "listenOnly": false
}`

**Comment by elaineo** [comment]
Try this:
'"terminateAtExistingDB": false,
    "listenOnly": true'

**Comment by anhdung-le** [comment]
I found the reason: it's the **mongo DB**
Simply remove blockDB (local if needed also) should do the trick!
Your config works too @elaineo!
Thanks & cheers!
