### ISSUE TITLE
Architecture proposal

### ISSUE THREAD

**Issue by yograterol** [ethereumproject/explorer#57]
Hi,

I'm following and working on ETC blockchain. And I think that we could improve a lot this explorer.

My proposal starts changing MongoDB for LevelDB (Thanks @elaineo for the advise)

We've some options to implement LevelDB.

The first, keeping JS as backend language we should use https://github.com/Level/levelup.

The second option B4F (Backend for frontend) - Backend with LevelDB (has changes in the architecture.):

- B4F with Nextjs to get server side render and the better features from React.
- Backend with RPC to expose all data and connect with the B4F.

What do you think? I would like to hear your opinion and starting to work ASAFP.

**Comment by elaineo** [comment]
I think LevelDB will be fairly easy to port. Let's go for it.

I'm not sure I understand the second option. Are you proposing to switch to React? Is there documentation for B4F?

**Comment by yograterol** [comment]
@elaineo thanks for your answer. I propose to use NextJS (https://github.com/zeit/next.js/), it will be a backend just to server the frontend.

And keep isolated the front end and the backend of the explorer, both will communicate through RPC calls.

**Comment by elaineo** [comment]
Okay. I think isolating the frontend and backend is a good idea. I have no problem with using NextJS to replace the current backend, but it sounds like it will be a fairly big project.

**Comment by yograterol** [comment]
@elaineo may be, I could do my best work to keep it small. I'll start to work and keeping you updated about the progress.
