### ISSUE TITLE
Ethereum Classic Transaction ID Problem

### ISSUE THREAD

**Issue by doctherock** [ethereumproject/explorer#58]
Hello,

im from Germany and im quite new in mining ethereum classic coins. I have earned 2 Coins the last 4 Days. The first coin i send to anycoin for a test-payout. Everything fine and it worked quite well.

The second coin i earned, i transferred to poloniex. Now i got a support Ticket from Poloniex which says "It appears you have forgotten to provide the transaction id of your deposit".

The Problem is that the 2 transactions are not displayed in my wallet. When i go to "See Transaction History" it opens are new window but there are no transactions displayed.

"No transactions found", but in the overview there is written "2 Transactions". What can i do now or perhaps u can help me. This would be very nice.

**Comment by elaineo** [comment]
the server database is in need of an upgrade. can you try http://gastracker.io to view your transaction history?

**Comment by doctherock** [comment]
Hello,

this side looks fine, but where do i see the transaction ID for the last
payment on Poloniex ?
My Wallet Adress ist 0x282fA96995BDb6fAFe50822b5AaEb86dbAf98EA4

Perhaps u can help me again. Sry im quite new here. Thx

2017-06-03 8:27 GMT+02:00 Elaine Ou <notifications@github.com>:

**Comment by realcodywburns** [comment]
Check at http://etcchain.com/addr/0x282fA96995BDb6fAFe50822b5AaEb86dbAf98EA4

**Comment by doctherock** [comment]
Ok nice, thx u a lot. I opened a GITHub Thread a few hours ago. Perhaps u
can close it. Thx a lot

2017-06-03 8:49 GMT+02:00 Cody Burns <notifications@github.com>:
