### ISSUE TITLE
Inaccessible web3 git pinned by package.json

### ISSUE THREAD

**Issue by RorschachRev** [ethereumproject/explorer#64]
"web3": "git://github.com/elaineo/web3.js#develop"
This ensures that any bugs caused during development in the underlying library will be inherited by your software and break, for some users, until that under development branch is fixed.

Additionally, npm install didn't have enough permissions by default for new users to actually get the code. I did a git clone and as a workaround:
"web3": "file:local_modules/web3"

Never pin the development/master version of another git.

**Comment by elaineo** [comment]
k, feel free to submit the fix as a PR.

**Comment by realcodywburns** [comment]
Close per PR #72
