### ISSUE TITLE
config.json ignored, latest first creates huge gaps 

### ISSUE THREAD

**Issue by RorschachRev** [ethereumproject/explorer#65]
I have declared specific blocks inside my config.json which were promptly ignored by grabber.js. I didn't immediately see the cause of this inside the source, copied the config.json to the parent directory and tried again with the same results.

By counting latest first, I have massive gaps all over my database. Since I can't declare which blocks to download, the gaps are persistent unless I start a new database (command lacking?), disconnect from the internet or prevent blockchain sync some other way, and then finish the extraction all in one attempt.

**Comment by elaineo** [comment]
if you set `terminateAtExistingDB` to `false`, that should populate any missing blocks.

**Comment by RorschachRev** [comment]
How do I get config.json to stop being ignored, to add things like that? It won't even pay attention to "quiet"

**Comment by elaineo** [comment]
are you running `node ./tools/grabber.js` ? it automatically reads from config.json.

**Comment by RorschachRev** [comment]
Please note that "quiet" mode is enabled in the config file:
[etc-explorer-issue65.txt](https://github.com/ethereumproject/explorer/files/1468371/etc-explorer-issue65.txt)

**Comment by elaineo** [comment]
oh, sorry about that. It looks for `config.json` in the local directory. it looks like you have the file in /tools/ so either run `grabber.js` in the tools directory, or move config.json to the root dir.

**Comment by RorschachRev** [comment]
confirmed that config.json in current working directory is expected behavior and working normally.
