### ISSUE TITLE
etherhub.io down

### ISSUE THREAD

**Issue by whilei** [ethereumproject/explorer#67]
![screen shot 2017-12-03 at 06 31 58](https://user-images.githubusercontent.com/10228550/33525373-c5694054-d7f3-11e7-8b40-2e9993e07ed1.png)

**Comment by whilei** [comment]
Just found `Find a permanent home for the explorer (register a domain name)` on the Trello... looks like known thing

**Comment by elaineo** [comment]
Yeah... a member of the community kindly donated server hosting for the explorer for a year, but couldn't afford to keep going after that.

**Comment by kimisan** [comment]
wow...let me setup a standby site with my Google Cloud server.

**Comment by elaineo** [comment]
thanks @kimisan ! @pyskell is also working on a proposal to get funding for some ETC nodes. That would reduce the cost of running a server a bit.

**Comment by kimisan** [comment]
Ok, glad to hear that. Thank you both! @elaineo @pyskell 
I will prepare a standby site first and regular maintain it.

**Comment by kimisan** [comment]
I almost finished the backup site,
but  i set listenOnly it to True
but it look like still keeping populate older block numbers...
PS: i clone the latest repo.
{
    "gethPort": 8545, 
    "blocks": [ {"start": 4975445, "end": "latest"}],
    "quiet": false,
    "terminateAtExistingDB": false,
    "listenOnly": true
}

**Comment by elaineo** [comment]
thanks a lot for creating this backup site kimisan! are you running `node ./tools/grabber.js` from the /tools/ directory?

**Comment by kimisan** [comment]
OK i run it now.
May you help me check the config setting is ok or not?
{
    "gethPort": 8545, 
    "blocks": [ {"start": 2000000, "end": "latest"}],
    "quiet": false,
    "terminateAtExistingDB": false,
    "listenOnly": true
}

**Comment by elaineo** [comment]
yup, that should only fetch the latest blocks.

**Comment by kimisan** [comment]
@elaineo , it look like the grabber.js does not synced finished.
Can I re-definition the config file to much short time.
Thank you

**Comment by elaineo** [comment]
@kimisan not sure i understand the question... when "listenOnly" is true, it should only be grabbing the latest blocks. is that working?

**Comment by kimisan** [comment]
wow, my account got frozen by Google Cloud due to "similar to Crypto mining activity"
Already write a letter ask them to fix it =.=

**Comment by elaineo** [comment]
oh no! you are just running the node with no mining, right? i haven't had problems running nodes before...

**Comment by kimisan** [comment]
after all, google cloud give my server back ...
But they delete all the file now ...
Under Recovering ^^

**Comment by elaineo** [comment]
okay, looks like we're getting some funding and a new server for hosting!
https://forum.ethereumclassic.org/t/block-explorer-proposal/92/4
