### ISSUE TITLE
Missing transactions

### ISSUE THREAD

**Issue by pcdinh** [ethereumproject/explorer#77]
Hi,

There is a bug in Explorer that prevents it from displaying transactions by account

http://etherhub.io/addr/0xa312ea325c9f520d58acfaf81786d929ad9ca896

=> no transactions

http://gastracker.io/addr/0xa312ea325c9f520d58acfaf81786d929ad9ca896

=> missing transactions

The expected result: https://etcchain.com/addr/0xa312ea325c9f520d58acfaf81786d929ad9ca896

Regards,

Dinh

**Comment by pcdinh** [comment]
Gastracker.io works today. Yesterday it didn't show 5 transactions as expected. Only 3.

etherhub.io still shows: No transactions found

**Comment by elaineo** [comment]
duplicate: https://github.com/ethereumproject/explorer/issues/54
