### ISSUE TITLE
Organization of issues backlog

### ISSUE THREAD

**Issue by realcodywburns** [ethereumproject/explorer#78]
Evaluate current issues and move to trello backlog for sprint planning. Update readme with issue/pr workflow.

assumed flow:
- issue created
- acceptance criteria defined
- added to backlog
- items in back log are worked through

https://trello.com/b/W3ftl57z/etc-block-explorer-development

**Comment by realcodywburns** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Organization of issues backlog #78](https://trello.com/c/ON43gxCh/15-organization-of-issues-backlog-78)

**Comment by elaineo** [comment]
is trello still used for any ETC projects? i believe ETCDEV is using github projects, which I prefer too https://github.com/orgs/ethereumproject/projects

**Comment by realcodywburns** [comment]
Yeah I  discovered by projects today and like it much better than trello
