### ISSUE TITLE
CircleCI Setup

### ISSUE THREAD

**Issue by matthewjamesr** [ethereumproject/explorer#8]
We should enable CI on our codebase. I am not sure how we have deployment to production setup currently but we should not leave pushing merged-PRs to production to a single point of failure.

I bring this up so we can operate more efficiently and push code changes quicker for endusers.

https://circleci.com/

**Comment by elaineo** [comment]
I don't have a preference either way, but it looks like other projects are using TravisCI. 
cc @jsmith-dev 

https://www.reddit.com/r/EthereumClassic/comments/4wbxg9/ethereum_project_adopts_travis_ci_for_pipeline/

**Comment by matthewjamesr** [comment]
@elaineo Sounds great as long as we implement and all of us are on the same platform. Thanks for the link, was news to me.
