### ISSUE TITLE
Setup a Slack to make development easier

### ISSUE THREAD

**Issue by Empty2k12** [ethereumproject/explorer#9]
Right now all communication is done via #1 which is very messy. Slack allows channels to be created. This would enhance development

**Comment by matthewjamesr** [comment]
We can use slack or telegram. You mean existing ETC slack? If you have link handy do share.

**Comment by Empty2k12** [comment]
@matthewjamesr Either there or a dedicated Slack for this project. Something like this https://github.com/outsideris/slack-invite-automation or https://github.com/rauchg/slackin could be used to get contributors onboarded!

**Comment by matthewjamesr** [comment]
@Empty2k12 I have used Slackin before. Easy to setup and can just deploy to a heroku free instance. Let goto the main slack and create our own channel then.

**Comment by Empty2k12** [comment]
@matthewjamesr Link? :laughing:

**Comment by elaineo** [comment]
can we connect it to this one? https://ethereumclassic.slack.com/messages/explorer/details/

**Comment by Empty2k12** [comment]
@elaineo Thats the one. Do you want to create a channel?
